#!/bin/bash
if ! declare -F "confirm_yes" > /dev/null 2>&1; then
  source "$D/user_prompts.sh"
fi
ms1=ANMF
ms2=ANIM


declare -a to_convert_or_delete
to_convert_or_delete=()
while IFS= read -r -d $'\0'; do
  to_convert_or_delete+=("$REPLY") # REPLY is the default
done < <(find "." -regex ".*.webp" -print0 2> /dev/null)

for i in "${to_convert_or_delete[@]}"; do
       grep -e $ms1 -e $ms2 $i	
	if [ $? -ne 1 ]; then
		mogrify -format gif $i
	else
		pngname=$(echo $i|sed s/webp/png/g)
	    dwebp $i -o $pngname
		if [ $? -eq 0 ]; then
			mv $i /tmp/
		else
			echo "something went wrong with $i"
			return 1
		fi
	fi
done
if confirm_yes "Clean out remaining .webp files? "; then
  echo " "
  find "." -regex ".*.webp" -exec rm -f {} \;
fi